name: catalyst
description: A new Flutter project.
publish_to: none
version: 1.0.1+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  swipeable_card_stack: ^0.0.5
  swipable_stack: ^2.0.0
  google_fonts: ^4.0.3
  url_launcher: ^6.1.6
  permission_handler: ^10.2.0
  equatable: ^2.0.3
  cloud_firestore: ^4.4.5
  image_picker: ^0.8.4+9
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0
  multi_select_flutter: ^4.1.3
  video_player: ^2.7.2
  chewie: ^1.7.1
  flutter_cache_manager: ^3.3.0
  font_awesome_flutter: null
  firebase_core: null
  firebase_messaging: ^14.6.9
  multiple_search_selection: ^2.5.0
  flutter_firebase_chat_core: 1.6.4
  intl: ^0.18.1
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  location: ^5.0.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_storage: ^11.1.0
  provider: ^6.0.5
  firebase_database: ^10.2.5
  firebase_core_platform_interface: ^4.8.0
  firebase_auth_mocks: ^0.12.0
  geoflutterfire2: ^2.3.15
  rxdart: ^0.27.7
  dropdown_search: ^5.0.6
  in_app_purchase: ^3.2.0
flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/videos/production_id_4881692.mp4
    - assets/env