-- With the user_id being SERIAL, we never need to submit a user_id 
-- argument or inject one in the query; it's autogenerated in the database.

-- NOTE: In your Flutter code, the Location widget (https://www.youtube.com/watch?v=65qbtJMltVk)
-- will be used to get the latitude and longitude coordinates of users.
-- Those will then be passed off to the backend, where a function
-- will be used to determine the user's city & country. Finally, those
-- values will be written to the database.

CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(254),
    password VARCHAR(60),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO users (
    first_name, 
    last_name, 
    email, 
    password
)
VALUES (
    'Rosie', 
    'Babbra', 
    'rosiebabbra@gmail.com', 
    '$2b$12$1uURkzpFb9gP9V0DeJCzTev2O.E6/BxBYbulG12pJGT5wXyntfwd2'
);